"""refactor organization model

Revision ID: b0a61c555d44
Revises: 9f09532a8f30
Create Date: 2026-08-18 07:27:15.451872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a61c555d44'
down_revision = '9f09532a8f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legal_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('trade_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=14),
               existing_nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('trade_name')
        batch_op.drop_column('legal_name')

    # ### end Alembic commands ###
